CREATE DATABASE Examen_Aarco;
GO
USE Examen_Aarco;
GO
CREATE TABLE Cat_Modelos(
Id INT PRIMARY KEY IDENTITY NOT NULL,
Modelo VARCHAR(50) UNIQUE NOT NULL,
Activo BIT NOT NULL DEFAULT 1
);
CREATE TABLE Cat_Descripciones(
Id INT PRIMARY KEY IDENTITY NOT NULL,
Descripcion VARCHAR(250) NOT NULL,
DescripcionId VARCHAR(36) UNIQUE NOT NULL,
Activo BIT NOT NULL DEFAULT 1
);
CREATE TABLE Cat_SubMarcas(
Id INT PRIMARY KEY IDENTITY NOT NULL,
SubMarca VARCHAR(50) UNIQUE NOT NULL,
Activo BIT NOT NULL DEFAULT 1
);
CREATE TABLE Marcas(
Id INT PRIMARY KEY IDENTITY NOT NULL,
Marca VARCHAR(50) UNIQUE NOT NULL,
Activo BIT NOT NULL DEFAULT 1
);
CREATE TABLE SubMarcas(
Id INT PRIMARY KEY IDENTITY NOT NULL,
Marca INT REFERENCES Marcas(Id) NOT NULL,
SubMarca INT REFERENCES Cat_SubMarcas(Id) NOT NULL,
Activo BIT NOT NULL DEFAULT 1
);

CREATE TABLE Modelos(
Id INT PRIMARY KEY IDENTITY NOT NULL,
SubMarca INT REFERENCES SubMarcas(Id) NOT NULL,
Modelo INT REFERENCES Cat_Modelos(Id) NOT NULL,
Activo BIT NOT NULL DEFAULT 1
);

CREATE TABLE Descripciones(
Id INT PRIMARY KEY IDENTITY NOT NULL,
Descripcion INT REFERENCES Cat_Descripciones(Id) NOT NULL,
Modelo INT REFERENCES Cat_Modelos(Id) NOT NULL,
SubMarca INT REFERENCES SubMarcas(Id) NOT NULL,
Activo BIT NOT NULL DEFAULT 1
);

 